openapi: "3.0.0"
info:
  title: OpenAPI Library
  version: "1.0"
servers:
  - url: http://localhost/v1.0

paths:
  /book:
    get:
      summary: List all books
      operationId: controllers.books_controller.read_all
      tags:
        - books
      parameters:
        - name: length
          in: query
          description: Number of books to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A page array of books
          content: {}

  /books/{bookname}:
    delete:
      summary: Book to delete
      operationId: controllers.books_controller.delete
      parameters:
        - description: The name of book to delete
          in: path
          name: bookname
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successfull deletion" 
