openapi: "3.0.0"
info:
  title: OpenAPI Book Library
  version: "1.0"
servers:
  - url: /v1.0
    description: Dev server

paths:
  /health:
    get:
      summary: Get health of service
      operationId: controllers.books_controller.health
      responses:
        '200':
          description: A string response
          content: {}
  /books:
    get:
      summary: List all books
      operationId: controllers.books_controller.read_all
      tags:
        - books
      parameters:
        - name: length
          in: query
          description: Number of books to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A page array of books
          content: {}
    post:
      summary: Insert book
      operationId: controllers.books_controller.create
      tags:
        - books
      requestBody:
          description: Book to create
          required: True
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  amount:
                    type: integer
                    format: int32
                    description: Number of times sold
                  city:
                    type: string
                    description: The location of book
                  author:
                    type: string
                    description: the author email
      responses:
        '201':
          description: Inserted book
          content: {}
        '400':
          description: Bad insert request
          content: {}

  /books/{bookname}:
    get:
      summary: List one book
      operationId: controllers.books_controller.read_one
      tags:
        - books
      parameters:
        - description: The name of book to read
          in: path
          name: bookname
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A book in json format
          content: {}
    delete:
      summary: Book to delete
      operationId: controllers.books_controller.delete
      parameters:
        - description: The name of book to delete
          in: path
          name: bookname
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successfull deletion" 
