apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore.fullname" . }}
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "bookstore.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
