# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    service: mongo
spec:
  selector:
      service: mongo
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  labels:
    name: database
  name: mongo
spec:
  selector:
    matchLabels:
      service: mongo # has to match .spec.template.metadata.labels
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo  # has to match .spec.selector.matchLabels
        enviroment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-container
          image: mongo
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
          resources:
            requests:
              cpu: "0.2"
              memory: 200Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume-mount
      dnsPolicy: ClusterFirst
      volumes:
      - name: mongo-volume-mount
        persistentVolumeClaim:
          claimName: mongo-pvc

