apiVersion: v1
kind: Service
metadata:
 name: mongo
 labels:
  app: mongo
spec:
 ports:
  - port: 27017
    targetPort: 27017
 clusterIP: None
 selector:
  role: mongo
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
 name: mongo
spec:
  selector:
    matchLabels:
      app: mongo # has to match .spec.template.metadata.labels
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo # has to match .spec.selector.matchLabels
        enviroment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-pv-storage
  volumeClaimTemplates:
  - metadata:
      name: mongo-pv-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
