apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteMany 
  hostPath:
    path: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteMany 
  resources:
    requests:
      storage: 1Gi
  volumeName: mongo-pv
  storageClassName: manual